<?php

use Drupal\auth0\Util\AuthHelper;

/**
 * @file
 * Auth0 module.
 */

define( 'AUTH0_DEFAULT_SCOPES', 'openid email profile' );
define( 'AUTH0_DEFAULT_SIGNING_ALGORITHM', 'RS256' );
define( 'AUTH0_DEFAULT_USERNAME_CLAIM', 'nickname' );
define( 'AUTH0_JWT_LEEWAY_DEFAULT', 180 );

/**
 * Replace a form with the lock widget.
 */
function auth0_theme() {
  return [
    'auth0_login' => [
      'template' => 'auth0-login',
      'variables' => [
        'domain' => NULL,
        'clientID' => NULL,
        'state' => NULL,
        'showSignup' => NULL,
        'offlineAccess' => FALSE,
        'widgetCdn' => NULL,
        'loginCSS' => NULL,
        'callbackURL' => NULL,
        'lockExtraSettings' => '{}',
        'scopes' => AUTH0_DEFAULT_SCOPES,
      ],
    ],
  ];
}

/**
 * Implements hook_library_info_build().
 */
function auth0_library_info_build() {
  $config = \Drupal::service('config.factory')->get('auth0.settings');
  return [
    'auth0.widget' => [
      'js' => [
        $config->get('auth0_widget_cdn') => [
          'type' => 'external',
        ],
      ],
    ],
  ];
}

/**
 * Use Refresh Token
 */
function auth0_signin_with_refresh_token($token) {
  $helper = new AuthHelper();

  return $helper->getUserUsingRefreshToken($token);
}